apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs-depl
  template:
    metadata:
      labels:
        app: docs-depl
    spec:
      containers:
        - image: us.icr.io/quantico-reader/quantico_docs:1.0.0
          name: docs-depl
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.190.105.41
          - 10.190.105.51
        searches:
          - quanticotrends.com
      restartPolicy: Always