apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs-depl
  template:
    metadata:
      labels:
        app: docs-depl
    spec:
      containers:
        - image: us.icr.io/quantico-reader/quantico_docs:1.0.0
          name: docs-depl
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.190.105.41
          - 10.190.105.51
        searches:
          - quanticotrends.com
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: docs-srv
  labels:
    app: docs-srv
spec:
  selector:
    app: docs-depl
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      protocol: TCP
      port: 3500
      targetPort: 3500
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docs-igrs
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    ingress.bluemix.net/custom-port: "protocol=https port=443;protocol=http port=80"
    ingress.bluemix.net/redirect-to-https: "True"
spec:
  tls:
    - hosts:
        - docs.quanticotrends.com
      secretName: quantico-ssl
  rules:
    - host: docs.quanticotrends.com
      http:
        paths:
          - backend:
              serviceName: docs-srv
              servicePort: 3000
            path: /
