apiVersion: v1
kind: Service
metadata:
  name: docs-srv
  labels:
    app: docs-srv
spec:
  selector:
    app: docs-depl
  externalTrafficPolicy: Cluster
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}