apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docs-depl
  template:
    metadata:
      labels:
        app: docs-depl
    spec:
      containers:
        - image: us.icr.io/quantico-reader/quantico_docs:2.0.0
          name: docs-depl
      dnsPolicy: None
      dnsConfig:
        nameservers:
          - 10.190.105.41
          - 10.190.105.51
        searches:
          - quanticotrends.com
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: docs-srv
  labels:
    app: docs-srv
spec:
  type: NodePort
  selector:
    app: docs-depl
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000